version: '2'

volumes:
  fcrepo:
  solr:
  db:
  redis:
  zk1:
  zk2:
  zk3:
  zkconf:
  app:

networks:
  external:
  internal:

services:
  zoo1:
    image: zookeeper
    restart: always
    environment:
      - ZOO_MY_ID=1
      - ZOO_SERVERS=server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    expose:
      - 2181
      - 2888
      - 3888
    volumes:
      - zk1:/data
      - zkconf:/conf
    networks:
      internal:
       aliases:
         - zookeeper_cluster
  zoo2:
    image: zookeeper
    restart: always
    environment:
      - ZOO_MY_ID=2
      - ZOO_SERVERS=server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    expose:
      - 2181
      - 2888
      - 3888
    volumes:
      - zk2:/data
      - zkconf:/conf
    networks:
      internal:
       aliases:
         - zookeeper_cluster
  zoo3:
    image: zookeeper
    restart: always
    environment:
      - ZOO_MY_ID=3
      - ZOO_SERVERS=server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    expose:
      - 2181
      - 2888
      - 3888
    volumes:
      - zk3:/data
      - zkconf:/conf
    networks:
      internal:
       aliases:
         - zookeeper_cluster

  solr:
    image: solr
    command: solr -c -f -z zookeeper_cluster:2181
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    expose:
      - 8983
    volumes:
      - .:/app
      - solr:/data
    networks:
      internal:

  # ZACH'S COMMENT: 
  # Fedora is consistently reported "down" by Hyky admin console.
  # I altered JAVA_OPTS in several ways to attempt a fix:
  # 1. Tried to EXPORT JAVA_OPTS='[some basic heap size constraints]' # fcrepo rejected custom heap sizes
  # 2. Tried environment: - JAVA_OPTS = "${JAVA_OPTS}" adding contents of repository.json directly to the host environment. fcrepo rejected this too.
  # 3. Best config was without including host settings:
    # -JAVA_OPTS="-Dfcrepo.modeshape.configuration=\"classpath:/config/minimal-default/repository.json\""
    # # 
  
  # Tomcat (Catalina) logs report an error, but continues to run:
  
# fcrepo_1 | 26-Jan-2017 22:25:41.058 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive /usr/local/tomcat/webapps/fcrepo.war
# fcrepo_1 | 26-Jan-2017 22:25:41.597 WARNING [localhost-startStop-1] org.apache.catalina.webresources.Cache.getResource Unable to add the resource at [/WEB-INF/lib/commons-validator-1.3.1.jar] to the cache because there was insufficient free space available after evicting expired cache entries - consider increasing the maximum size of the cache
# fcrepo_1 | 26-Jan-2017 22:25:41.608 WARNING [localhost-startStop-1] org.apache.catalina.webresources.Cache.getResource Unable to add the resource at [/WEB-INF/lib/modeshape-common-4.5.0.Final.jar] to the cache because there was insufficient free space available after evicting expired cache entries - consider increasing the maximum size of the cache
    
  fcrepo:
    image: cbeer/fcrepo4
    expose:
      - 8983
    volumes:
      - fcrepo:/data
    environment:
      - JAVA_OPTS="${JAVA_OPTS} -Dfcrepo.modeshape.configuration=\"classpath:/config/minimal-default/repository.json\""
    networks:
      internal:

  db:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      internal:

# Zach:
# the app container dies, but it doesn't appear to die on error
  app:
    build: .
    environment:
      - REDIS_HOST=redis_cluster
      - REDIS_SENTINEL_HOST=redis_sentinel
      - DATABASE_URL=postgresql://postgres@db/postgres
      - FEDORA_URL=http://fcrepo:8983/fedora/rest
      - SOLR_URL=http://solr:8983/solr/
      - SETTINGS__ACTIVE_JOB__QUEUE_ADAPTER=sidekiq
      - SETTINGS__SOLR__URL=http://solr:8983/solr/
      - SETTINGS__ZOOKEEPER__CONNECTION_STR=zookeeper_cluster:2181/configs
      - RAILS_ENV=production
      - RAILS_SERVE_STATIC_FILES=true
      - RAILS_LOG_TO_STDOUT=true
      - SECRET_KEY_BASE=asdf
      - RAILS_CACHE_STORE_URL=memcache
    volumes:
      - app:/data/public/uploads
    networks:
      internal:

# Zach:
# this containers persists, is outward facing, and stores the app.

  web:
    extends: app
    command: bundle exec rails server -p 3000 -b '0.0.0.0'
    depends_on:
      - db
      - solr
      - fcrepo
      - redis_sentinel
      - zoo1
      - zoo2
      - zoo3
      - memcache
      - db_migrate
    expose:
      - 3000

  workers:
    extends: app
    command: bundle exec sidekiq
    depends_on:
      - db
      - solr
      - fcrepo
      - redis_sentinel
      - zoo1
      - zoo2
      - zoo3
      - initialize_app
      - db_migrate
  
  initialize_app:
    extends: app
    restart: on-failure
    command: bundle exec rails zookeeper:upload
    depends_on:
      - zoo1
      - zoo2
      - zoo3

  db_migrate:
    extends: app
    restart: on-failure
    command: bundle exec rails db:migrate
    depends_on:
      - db

  lb:
    image: dockercloud/haproxy:1.5.3
    links:
      - web
    environment:
      - DOCKER_TLS_VERIFY
      - DOCKER_HOST
      - DOCKER_CERT_PATH
    volumes:
      - $DOCKER_CERT_PATH:$DOCKER_CERT_PATH
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      internal:
      external:

  redis_primary:
    extends: redis
    command: redis-server
    volumes:
      - redis:/data

  redis:
    image: redis:3
    command: redis-server --slaveof redis_primary 6379
    networks:
      internal:
        aliases:
          - redis_cluster

# Redit_sentinal container fails on config
# I haven't tried anything to fix this.

# redis_sentinel_1  | *** FATAL CONFIG FILE ERROR ***
# redis_sentinel_1  | Reading the configuration file, at line 10
# redis_sentinel_1  | >>> 'sentinel monitor redis_cluster redis_primary 6379 2'
# redis_sentinel_1  | Duplicated master name.
# hyku_redis_sentinel_1 exited with code 1


  redis_sentinel:
    image: s7anley/redis-sentinel-docker
    environment:
      - MASTER=redis_primary
      - MASTER_NAME=redis_cluster
    links:
      - redis_primary
    networks:
      internal:

  memcache:
    image: memcached
    networks:
      internal:
